# Generated by Django 4.2.16 on 2026-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='test_name',
            field=models.CharField(default='CSA Mock Exam', max_length=100),
        ),
    ]
