# Generated by Django 4.2.16 on 2026-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_SELECT', 'Multiple Select')], default='SINGLE_CHOICE', max_length=50)),
                ('topic', models.CharField(choices=[('Automation', 'Automation'), ('Collaboration', 'Collaboration'), ('DB & Security', 'DB & Security'), ('Instance', 'Instance'), ('Integration', 'Integration'), ('Platform', 'Platform')], max_length=50)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('option_e', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answers', models.CharField(help_text="Comma-separated options, e.g., 'A,C,D'", max_length=100)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
